#!/bin/sh -e
#
# 2021 Mesar Hameed (mesar.hameed at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "$__global/explorer/os")
case "$os" in
    debian)
        :
    ;;
    ubuntu)
        :
    ;;
    *)
        echo "OS $os currently not supported" >&2
        exit 1
    ;;
esac

export CDIST_ORDER_DEPENDENCY=on

# install packages
__package ipset

__file /etc/init.d/ipset-persistent --mode 0755 --source "${__type}/files/ipset-persistent"
__file /usr/local/bin/ipsets-restore --mode 0755 --source "${__type}/files/ipsets-restore"
__file /usr/local/bin/ipsets-save --mode 0755 --source "${__type}/files/ipsets-save"
__systemd_unit ipset-persistent --enablement-state enabled --restart

unset CDIST_ORDER_DEPENDENCY
